name: mpd-splines-public
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.8.19
- pip
- cmake
- ninja
- eigen
- boost=1.82.0
- assimp
- octomap
- qhull
- tinyxml2
- urdfdom
- urdfdom_headers
- console_bridge
- pinocchio=2.7.*
- hpp-fcl=2.4.*
- ffmpeg
- gcc_linux-64=12
- gxx_linux-64=12
- cudnn==8.9.7.29
- pip:
  - --extra-index-url https://download.pytorch.org/whl/cu118
  - absl-py==2.1.0
  - antlr4-python3-runtime==4.9.3
  - black==24.8.0
  - cachetools==5.3.3
  - castxml==0.4.5
  - catkin-pkg==1.0.0
  - certifi==2022.12.7
  - cfgv==3.4.0
  - charset-normalizer==2.1.1
  - cholespy==1.0.0
  - click==8.1.7
  - cmake==3.25.0
  - colour==0.1.5
  - ConfigArgParse==1.7
  - Cython==3.0.11
  - decorator==4.4.2
  - dirsync==2.2.5
  - distlib==0.3.9
  - distro==1.9.0
  - docker-pycreds==0.4.0
  - docutils==0.20.1
  - dotmap==1.3.30
  - eigenpy==3.5.1
  - einops==0.8.0
  - -e ./deps/experiment_launcher
  - filelock==3.13.1
  - freetype-py==2.4.0
  - fsspec==2024.6.1
  - functorch==2.0.0
  - gdown==3.10.1
  - ghalton==0.6.2
  - gitdb==4.0.11
  - GitPython==3.1.43
  - google-auth==2.32.0
  - google-auth-oauthlib==1.0.0
  - grpcio==1.64.1
  - h5py==3.11.0
  - hpack==4.0.0
  - huggingface-hub==0.23.4
  - Hydra==2.5
  - identify==2.6.1
  - idna==3.4
  - imageio==2.34.2
  - imageio-ffmpeg==0.5.1
  - importlib_metadata==8.0.0
  - imutils==0.5.4
  - -e ./deps/isaacgym/python
  - Jinja2==3.1.3
  - joblib==1.4.2
  - lit==15.0.7
  - lxml==5.2.2
  - Markdown==3.6
  - mesh-to-sdf==0.0.15
  - moviepy==1.0.3
  - -e ./mpd/motion_planning_baselines
  - -e ./
  - mpmath==1.3.0
  - mypy_extensions==1.1.0
  - networkx
  - ninja==1.11.1.1
  - nodeenv==1.9.1
  - oauthlib==3.2.2
  - omegaconf==2.3.0
  - opencv-contrib-python==4.10.0.84
  - opencv-python==4.10.0.84
  - pandas==2.0.3
  - paramz==0.9.6
  - pathspec==0.12.1
#  - -e ./deps/pybullet_ompl
  - pin==2.7.0
  - plotly==5.22.0
  - pre-commit==3.5.0
  - proglog==0.1.10
  - protobuf==5.27.2
  - psutil==6.0.0
  - pyasn1==0.6.0
  - pyasn1_modules==0.4.0
  - pybullet==3.2.6
  - pycollada==0.6
  - pygame==2.6.0
  - pygccxml==2.5.0
  - pyglet==2.0.15
  - PyOpenGL==3.1.0
  - pyplusplus==1.8.5
  - pyrender==0.1.45
  - pytz==2024.1
  - PyWavelets==1.4.1
  - PyYAML==6.0.1
  - regex==2024.5.15
  - requests==2.28.1
  - requests-oauthlib==2.0.0
  - rospkg==1.5.1
  - rsa==4.9
  - safetensors==0.4.3
  - scikit-image==0.19.3
  - scikit-learn==1.3.2
  - scikit-video==1.1.11
  - scipy==1.10.1
  - seaborn==0.13.2
  - sentence-transformers==3.0.1
  - sentry-sdk==2.8.0
  - setproctitle==1.3.3
  - shapely==2.0.4
  - six==1.14.0
  - smmap==5.0.1
  - sobol-seq==0.2.0
  - sympy==1.12
  - tabulate==0.9.0
  - tenacity==8.5.0
  - tensorboard==2.14.0
  - tensorboard-data-server==0.7.2
  - threadpoolctl==3.5.0
  - tifffile==2023.7.10
  - tokenizers==0.19.1
  - tomli==2.0.1
  - torch==2.0.0+cu118
  - torch-kmeans==0.2.0
  - torch-summary==1.4.5
  - -e ./mpd/torch_robotics
  - torchdiffeq==0.2.4
  - -e ./deps/theseus/torchkin
  - torchlie==0.1.0
  - torchvision==0.15.1+cu118
  - tqdm==4.43.0
  - transformers==4.42.3
  - trimesh==4.4.2
  - triton==2.0.0
  - typing_extensions==4.9.0
  - tzdata==2024.1
  - urdf_parser_py==0.0.4
  - urdfpy==0.0.22
  - urllib3==1.26.13
  - vendi-score==0.0.3
  - virtualenv==20.31.2
  - wandb==0.17.4
  - Werkzeug==3.0.3
  - zstandard==0.22.0
variables:
  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: 'True'
