model_dir_ddpm_bspline: ${MPDLX_DATA_ROOT}/data_trained_models/launch_train_diffusion_models-v04_2024-09-18_08-12-54/generative_model_class___GaussianDiffusionModel/dataset_subdir___EnvSpheres3D-RobotPanda-joint_joint-one-RRTConnect/dataset_file_merged___dataset_merged_doubled.hdf5/context_ee_goal_pose___True/unet_input_dim___32/unet_dim_mults_option___1/context_q_out_dim___128/context_ee_goal_pose_out_dim___128/context_combined_out_dim___128/bspline_num_control_points_desired___24/parametric_trajectory_class___ParametricTrajectoryBspline/0
model_dir_cvae_bspline: ${MPDLX_DATA_ROOT}/data_trained_models/launch_train_cvae_models-v04_2024-09-18_08-14-47/generative_model_class___CVAEModel/dataset_subdir___EnvSpheres3D-RobotPanda-joint_joint-one-RRTConnect/dataset_file_merged___dataset_merged_doubled.hdf5/context_ee_goal_pose___True/unet_input_dim___32/unet_dim_mults_option___1/context_q_out_dim___128/context_ee_goal_pose_out_dim___128/context_combined_out_dim___128/bspline_num_control_points_desired___24/parametric_trajectory_class___ParametricTrajectoryBspline/0
model_dir_ddpm_waypoints: ${MPDLX_DATA_ROOT}/data_trained_models/launch_train_diffusion_models-v04_2024-11-11_10-27-59/generative_model_class___GaussianDiffusionModel/dataset_subdir___EnvSpheres3D-RobotPanda-joint_joint-one-RRTConnect/dataset_file_merged___dataset_merged_doubled.hdf5/context_ee_goal_pose___True/unet_input_dim___32/unet_dim_mults_option___1/context_q_out_dim___128/context_ee_goal_pose_out_dim___128/context_combined_out_dim___128/bspline_num_control_points_desired___24/parametric_trajectory_class___ParametricTrajectoryWaypoints/0
model_selection: bspline
min_distance_q_pos_start_goal: 3.5
env_id_replace: null
grasped_object: null
obstacle_cutoff_margin_extra: 0.05
margin_for_dense_collision_checking: 0.0
num_T_pts: 128
trajectory_duration: 10.0
phase_time_class: PhaseTimeLinear
project_gradient_hierarchy: false
costs:
  CostTaskSpaceCollisionObjects:
    weight: 10.0
    use_only_on_extra_objects: false
  CostTaskSpaceCollisionSelf:
    weight: 1.0
  CostJointSpaceJointLimits:
    weight: 1.0
  CostTaskSpaceEEGoalPose:
    weight: 1.0
  CostJointSpaceVelocity:
    weight: 0.01
  CostJointSpaceAcceleration:
    weight: 0.001
n_trajectory_samples: 100
best_trajectory_selection: shortest_path_length
planner_alg: mpd
diffusion_sampling_method: dpm_solver_pp
compute_costs_with_xrecon: false
n_diffusion_steps_without_noise: 0
extra_mp_steps: 0
ddim:
  t_start_guide_steps_fraction: 0.3
  ddim_sampling_timesteps: 15
  ddim_eta: 0.5
  ddim_skip_type: quadratic
  ddim_scale_grad_prior: 0.25
  n_guide_steps: 4
  guide_lr: 1.0
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
diffusion_prior_then_guide:
  n_guide_steps: 12
  guide_lr: 0.01
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
ddpm:
  t_start_guide_steps_fraction: 0.2
  prior_weight_with_guide: 0.95
  noise_std: 0.7
  n_guide_steps: 2
  guide_lr: 0.01
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
dpm_solver:
  t_start_guide_steps_fraction: 0.2
  dpm_solver_steps: 26
  dpm_solver_order: 2
  dpm_solver_method: multistep
  dpm_solver_algorithm_type: dpmsolver++
  dpm_solver_skip_type: logSNR
  dpm_solver_solver_type: dpmsolver
  dpm_solver_denoise_to_zero: true
  use_continuous_time: true
  lower_order_final: false
  prior_weight_with_guide: 0.85
  n_guide_steps: 2
  guide_lr: 0.06
  max_perturb_x: 0.05
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
  scale_grad_by_std: false
unipc:
  t_start_guide_steps_fraction: 0.08
  unipc_steps: 20
  unipc_order: 2
  unipc_skip_type: logSNR
  unipc_variant: bh1
  unipc_lower_order_final: true
  unipc_denoise_to_zero: false
  use_continuous_time: false
  clip_denoised: false
  clip_denoised_min: -1.0
  clip_denoised_max: 1.0
  prior_weight_with_guide: 0.97
  n_guide_steps: 2
  guide_lr: 0.03
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
  scale_grad_by_std: false
gp_prior_then_guide:
  n_guide_steps: 12
  guide_lr: 0.01
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
knn_prior_then_guide:
  n_guide_steps: 12
  guide_lr: 0.01
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
cvae_prior_then_guide:
  n_guide_steps: 12
  guide_lr: 0.01
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
rrtconnect_then_guide:
  n_guide_steps: 12
  guide_lr: 0.01
  max_perturb_x: 0.15
  clip_grad: true
  clip_grad_rule: value
  max_grad_norm: 1.0
  max_grad_value: 1.0
